server:
  port: 8080
  servlet.context-path:
logging:
  level:
    root: info
    com.spring: DEBUG
  file:
    name: logs/debug.log

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stars?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true